import Head from "next/head";
import Image from "next/image";
import FontCard from "../components/FontCard";
import styles from "./index.module.css";

export default function Home() {
  return (
    <main className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.topLeft}>
        <p className={styles.label}> Font Preference</p>
        <h1 className={styles.question}> Choose a font that feels</h1>
        <h1 className={styles.adjective}> Playful</h1>
      </div>

      <div className={styles.topRight}>
        <FontCard></FontCard>
      </div>
      <div className={styles.bottomRight}>
        <FontCard></FontCard>
      </div>
      <div className={styles.bottomLeft}>
        <p>Q1/10</p>
      </div>
    </main>
  );
}
