import Head from "next/head";
import Image from "next/image";
import React, { useState, useEffect } from "react";
import FontCard from "../components/FontCard";
import styles from "./index.module.css";
import Navbar from "../components/Navbar";
import { motion, AnimatePresence } from "framer-motion";

export default function Home() {
  //count questions
  const [qCount, setQCount] = useState(0);

  const handleQCount = () => {
    setQCount(qCount + 1);
    console.log("clicked");
  };

  //mount and unmounct card
  const [cardState, setCardState] = useState(true);

  useEffect(() => {
    console.log(cardState);

    //remount
    if (!cardState) {
      setTimeout(() => {
        //your code to be executed after 1 second
        setCardState(!cardState);
      }, 1000);
    }
  }, [cardState]);

  return (
    <motion.main
    // initial={{ opacity: 0 }} animate={{ opacity: 1 }}
    >
      <Head>
        <title>Crowdsourcing Font Preferences</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.globalContainer}>
        <Navbar></Navbar>
        <div className={styles.container}>
          <div className={styles.leftCol}>
            <div className={styles.topLeft}>
              <h2 className={styles.question}> Choose a font that feels</h2>
              <h1 className={styles.adjective}> Playful</h1>
            </div>

            <h3 className={styles.bottomLeft}>Q{qCount}/10</h3>
          </div>
          <div className={styles.rightCol}>
            {cardState && (
              <motion.div
                className={styles.topRight}
                onClick={() => {
                  setCardState(!cardState);
                  setQCount(qCount + 1);
                }}
              >
                <FontCard></FontCard>
              </motion.div>
            )}

            {cardState && (
              <motion.div
                onClick={() => {
                  setCardState(!cardState);
                  setQCount(qCount + 1);
                }}
                className={styles.bottomRight}
              >
                <FontCard></FontCard>
              </motion.div>
            )}
          </div>
        </div>
      </div>
    </motion.main>
  );
}
