import Head from "next/head";
import Image from "next/image";
import Card from "../components/card";
import styles from "/styles/index.module.css";
import styled from "styled-components";

const Main = styled.main`
  min-height: 100vh;
  display: grid;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: 1fr 1fr;
`;

const CardOneContainer = styled.div`
  grid-column-start: 2;
  grid-row-start: 1;
  height: 100%;
  padding: 20px;
`;

const CardTwoContainer = styled.div`
  grid-column-start: 2;
  grid-row-start: 2;
  height: 100%;
  padding: 20px;
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <CardOneContainer>
          <Card></Card>
        </CardOneContainer>
        <CardTwoContainer>
          <Card></Card>
        </CardTwoContainer>
      </Main>
    </div>
  );
}
