import Head from "next/head";

export default function HeadComp() {
  return (
    <Head>
      <title>What&apos;s your type?</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
